### ISSUE TITLE
Pullup Resistors Needed for I2C Isolator

### ISSUE THREAD

**Issue by RonaldThomas** [TinkerMill/tinkerAccess#30]
From Todd Franks:

> I am able to get the LCD to work on J8 by adding 10k pullups to the J9 connector. So with nothing connected to J9 (no pullups) the isolator thinks the J9 side is driving, pulling the non-isolated side low and thus not allowing anything to work on the non-isolated side. The isolated side needs some default high value pullups so when nothing is connected, it will still work.

**Comment by lttech-llc** [comment]
Fixed in PCB rev 1.4
