### ISSUE TITLE
CONTRIBUTION

### ISSUE THREAD

**Issue by salemsifeddine** [TinkerMill/tinkerAccess#52]
Hi !
i saw this your project and i really liked it , i have a bachelor degree in electrical engineering this year and i choosed a access control system it is an iot project with a website dashboard to give the statistics and some other information, so sir if i can have your permission to send me the detail of this project  , it would be a great pleasure 

this my email: salemsifeddine1@gmail.com
thank you!

**Comment by JStech** [comment]
What details are you looking for? If you browse the repo, you'll find the hardware specifications as well as all the software.
